### ISSUE TITLE
many crab failures due to sklearn

### ISSUE THREAD

**Issue by jpata** [jpata/tthbb13#112]
About 25% percent of my ttH pilot jobs failed due to not being able to find `sklearn`
I suppose this is about the IB dirs because I see there

~~~
== CMSSW: ls: cannot access /cvmfs/cms-ib.cern.ch/week0/: No such file or directory
~~~

Sites are T2_US_MIT, T2_US_Florida (which I forgot to blacklist), T2_US_UCSD, T2_US_Wisconsin. We could blacklist them all, at the cost of running slower, but I'm not sure about it...
@gkasieczka 

http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=Joosep+Pata&refresh=60&table=Jobs&p=1&records=-1&activemenu=2&status=failed&site=&tid=160810_225429%3Ajpata_crab_ttHTobb_Aug11_pilot_v1

**Comment by gkasieczka** [comment]
The sites I checked have the IB available but only "week1" and not "week0" that we use. Will prepare a workaround that checks for both.

**Comment by jpata** [comment]
also `T2_UK_London_IC`, it's slightly problematic...

**Comment by jpata** [comment]
Data processing needs https://github.com/jpata/tthbb13/pull/122

**Comment by jpata** [comment]
see https://github.com/jpata/tthbb13/issues/124
