### ISSUE TITLE
MulticlassAnalyzer pickle file

### ISSUE THREAD

**Issue by jpata** [jpata/tthbb13#113]
**test failure**: `python tests.py` still fails on `MEAnalysis_heppy.py` because MulticlassAnalyzer looks for the pickle file in a relative path, need to introduce it in `MEAnalysis_cfg_heppy.py`.

```
  File "/mnt/t3nfs01/data01/shome/jpata/tth/sw/CMSSW/python/TTH/MEAnalysis/MulticlassAnalyzer.py", line 30, in __init__
    pickle_file = open(self.pickle_filename, "r")
IOError: [Errno 2] No such file or directory: 'BDT.pickle'
```

**Comment by jpata** [comment]
Good for you @gkasieczka ?

```
mv ./MEAnalysis/crab_vhbb/BDT.pickle ./MEAnalysis/data/BDT.pickle
```

**Comment by gkasieczka** [comment]
Fine (also remember to change in multicrab.py)
