### ISSUE TITLE
recipe for lumi

### ISSUE THREAD

**Issue by jpata** [jpata/tthbb13#129]
Currently the only way to calculate lumi from `MakeDatasetFiles.py` is using brilcalc on lxplus:

http://cms-service-lumi.web.cern.ch/cms-service-lumi/brilwsdoc.html

For each json:

```
export PATH=$HOME/.local/bin:/afs/cern.ch/cms/lumi/brilconda-1.0.3/bin:$PATH
brilcalc lumi -b "STABLE BEAMS" --normtag=/afs/cern.ch/user/l/lumipro/public/normtag_file/normtag_DATACERT.json -i input.json -u /pb
```

Would be good to have it simplified.

**Comment by gkasieczka** [comment]
Automated by:
https://github.com/jpata/tthbb13/blob/meanalysis-80x/MEAnalysis/python/calcLumis.py
